### PR TITLE
Add JAX implementation of MINE

### PR DESCRIPTION
**Pull request by pawel-czyz**
Hi @grfrederic, this PR replaces the PyTorch implementation of MINE with the JAX one.

However, it's the simplest one replacement. In particular, it does *not* have the following utilities:
  - Training/test split.
  - Early stopping.

### CODE REVIEW

**Comment by grfrederic** [comment]
once we merge the other branch and rebase this, it will be much easier to track changes

**Comment by grfrederic** [comment]
We don't have early stopping for our other neural estimators either. Train/test split could be nice, since we know that large networks can overfit on our tasks (at least when using InfoNCE).

**Comment by pawel-czyz** [comment]
True! I think it should go into another PR, though. (I think it's possible to somehow unify the implementations we currently have, so refactoring would be a good thing to do alongside train/test split utilities).

**Review by grfrederic — APPROVED** [review]
lgtm

**Pull request merged**
