### PR TITLE
Transition to new API

### PR DESCRIPTION
**Pull request by grfrederic**
Related to #67.

For now, together with @pawel-czyz I've worked out the skeleton for our new API.

### CODE REVIEW

**Comment by grfrederic** [comment]
I've "fixed" unit test, meaning they pass now. However, there is still some problems:

1. We have a lot of copied code when testing estimators. I suggest we write a generic `test_estimator` function, and then use that for all of them.
2. We could then have a group of easy tests which all estimators should pass, and then some specific tests for estimators we think should perform better
3. Since our external estimators now share the same interface, we can use the same function to test them also, just with a pytest `requires_r`
4. I suggest instead of building the sampler every time, we have a TEST_TASKS list (which can be borrowed from our BENCHMARK list)

**Comment by grfrederic** [comment]
In particular, one of the problems we have is that although neural estimators are very good for more complex tasks, we test them on very simple tasks where they seem to overestimate MI.

**Comment by grfrederic** [comment]
SORRY I NAMED THE LAST COMMIT WRONG, IT SHOULD BE "add studen-t tasks" :)))

**Review by pawel-czyz — APPROVED** [review]

**Comment by pawel-czyz** [comment]
LGTM!

**Pull request merged**
